### PR TITLE
do not require login, in order for Build to work + some graphlist styling

### PR DESCRIPTION
**Pull request by mariakleiner**
maybe we shouldn't even persist them at all, if there is no owner? 
for now i just changed it to always show owner in the graph card, to avoid confusion. and i tweaked the colors a bit so that graph don't look disabled:
Screenshot 2023-09-08 at 4 03 53 PM
WDYT?

### CODE REVIEW

**Review by sjmiles — APPROVED** [review]
Prefer "anonymous" to "unknown" if that's easy. :)

**Comment by sjmiles** [comment]
Persisting in local-storage is free for us, right? Do you mean publish?

Can/does local-anonymous work in Run/

**Comment by mariakleiner** [comment]
> Prefer "anonymous" to "unknown" if that's easy. :)

done!

**Comment by mariakleiner** [comment]
> Persisting in local-storage is free for us, right? Do you mean publish?
> 
> Can/does local-anonymous work in Run/

good catch - Run was broken in a couple different ways, all known ways fixed now :)

PS: local persistence and ownership may be weird, if you login/out and/or use different users. but i think we can address it later.

**Pull request merged**
