### PR TITLE
Run to support graph search by name only, and bump README Run version

### PR DESCRIPTION
**Pull request by mariakleiner**
now that the published graphs are grouped by the owner's name, the 
`.../Run/?graph=GRAPH-NAME`
links stop working and need to be `Run/?graph=owner/GRAPH-NAME`.
so i added support to search for them, if it's not accessible by just the name, so that either works...

### CODE REVIEW

**Review by sjmiles — CHANGES_REQUESTED** [review]
I factored the 'find a graph' stuff in #39 .

Hopefully it's easy to move these changes there?

**Comment by mariakleiner** [comment]
> I factored the 'find a graph' stuff in #39 .
> 
> Hopefully it's easy to move these changes there?

I think you already updated `Run/web/main.js` in your PR, so I can just revert my changes here!

**Comment by sjmiles** [comment]
> > I factored the 'find a graph' stuff in #39 .
> > Hopefully it's easy to move these changes there?
> 
> I think you already updated `Run/web/main.js` in your PR, so I can just revert my changes here!

Does this mean I accidentally broke it in a good way, lol?

**Comment by mariakleiner** [comment]
addressed comment PTAL

**Review by sjmiles — APPROVED** [review]

**Pull request merged**
